BCR/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BCR.Models;
using Interfaces;
using Interfaces.Impl;
using Library;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Models;
using Newtonsoft.Json;

namespace BCR.Controllers
{
    public class AdminController : BaseController
    {
        public JwtClaim claim;
        public ISystemService systemService;
        private ISystemService SystemService
        {
            get
            {
                if (systemService == null)
                {
                    systemService = new SystemService();
                }
                return systemService;
            }
        }
        public static string connstr = "";
        public AdminController(IHttpContextAccessor accessor, IConfiguration configuration) : base(accessor, configuration)
        {
            connstr = configuration["connstr:mysql"];
        }
        #region areainfo

        [PermitFilter]
        public IActionResult Area()
        {
            claim = (JwtClaim)_accessor.HttpContext.Items["user"];
            ViewBag.username = claim.username;
            ViewBag.area = claim.area;
            return View();
        }
        [PermitFilter]
        public string getArea()
        {
            claim = (JwtClaim)_accessor.HttpContext.Items["user"];
            List<SYS_AREA> model = SystemService.getArea(connstr);
            LayTableModel<List<SYS_AREA>> table = new LayTableModel<List<SYS_AREA>>();
            table.message = "success";
            table.code = 200;
            table.total = model.Count;
            table.rows = new Rows<List<SYS_AREA>>();
            table.rows.item = new List<SYS_AREA>();
            table.rows.item = model;
            return JsonConvert.SerializeObject(table);
        }
        [PermitFilter]
        public IActionResult editArea(int id)
        {
            claim = (JwtClaim)_accessor.HttpContext.Items["user"];
            ViewBag.username = claim.username;
            ViewBag.area = claim.area;
            List<SYS_AREA> model = SystemService.getArea(connstr);
            var res = model.Where(m => m.ID == id).FirstOrDefault();
            ViewBag.model = res;
            return View();
        }
        [PermitFilter]
        public IActionResult addArea()
        {
            claim = (JwtClaim)_accessor.HttpContext.Items["user"];
            ViewBag.username = claim.username;
            ViewBag.area = claim.area;
            ViewBag.model = null;
            return View("editArea");
        }
        [PermitFilterAttribute]
        [HttpPost]
        public ResponseResult<string> addArea([FromQuery]string token, string name, string abb)
        {
            claim = (JwtClaim)_accessor.HttpContext.Items["user"];
            try
            {
                if (string.IsNullOrEmpty(name)||string.IsNullOrEmpty(abb))
                {
                    return ResponseResult<string>.Error("参数异常");
                }
                SYS_AREA area = new SYS_AREA { NAME=name,ABBREVIATION=abb};
                var b = SystemService.addArea(area, connstr);
                if (b)
                {
                    return ResponseResult<string>.Success("操作成功", "操作成功");
                }
                else
                {
                    return ResponseResult<string>.Success("操作失败", "操作失败");
                }
            }
            catch (Exception ex)
            {
                return ResponseResult<string>.Error("系统异常");
            }
        }

        #endregion

        #region roominfo

        [PermitFilter]
        public IActionResult RoomInfo()
        {
            claim = (JwtClaim)_accessor.HttpContext.Items["user"];
            ViewBag.username = claim.username;
            ViewBag.area = claim.area;
            return View();
        }
        [PermitFilter]
        public string getRoom()
        {
            claim = (JwtClaim)_accessor.HttpContext.Items["user"];
            List<SYS_ROOMINFO> model = SystemService.getRoom(connstr);
            LayTableModel<List<SYS_ROOMINFO>> table = new LayTableModel<List<SYS_ROOMINFO>>();
            table.message = "success";
            table.code = 200;
            table.total = model.Count;
            table.rows = new Rows<List<SYS_ROOMINFO>>();
            table.rows.item = new List<SYS_ROOMINFO>();
            table.rows.item = model;
            return JsonConvert.SerializeObject(table);
        }
        [PermitFilter]
        public IActionResult editRoom(int id)
        {
            claim = (JwtClaim)_accessor.HttpContext.Items["user"];
            ViewBag.username = claim.username;
            ViewBag.area = claim.area;
            List<SYS_ROOMINFO> model = SystemService.getRoom(connstr);
            var res = model.Where(m => m.ID == id).FirstOrDefault();
            ViewBag.model = res;
            return View();
        }
        
        [PermitFilter]
        public IActionResult addRoom()
        {
            claim = (JwtClaim)_accessor.HttpContext.Items["user"];
            ViewBag.username = claim.username;
            ViewBag.area = claim.area;
            ViewBag.model = null;
            return View("editRoom");
        }
        [PermitFilterAttribute]
        [HttpPost]
        public ResponseResult<string> addRoom([FromQuery]string token, string name, int area,int status)
        {
            claim = (JwtClaim)_accessor.HttpContext.Items["user"];
            try
            {
                if (string.IsNullOrEmpty(name))
                {
                    return ResponseResult<string>.Error("参数异常");
                }
                SYS_ROOMINFO room = new SYS_ROOMINFO { NAME = name,AREA=area,STATUS=status};
                var b = SystemService.addRoom(room, connstr);
                if (b)
                {
                    return ResponseResult<string>.Success("操作成功", "操作成功");
                }
                else
                {
                    return ResponseResult<string>.Success("操作失败", "操作失败");
                }
            }
            catch (Exception ex)
            {
                return ResponseResult<string>.Error("系统异常");
            }
        }

        #endregion

        #region userinfo

        [PermitFilter]
        public IActionResult UserInfo()
        {
            claim = (JwtClaim)_accessor.HttpContext.Items["user"];
            ViewBag.username = claim.username;
            ViewBag.area = claim.area;
            return View();
        }
        [PermitFilter]
        public string getUser()
        {
            claim = (JwtClaim)_accessor.HttpContext.Items["user"];
            List<SYS_USER> model = SystemService.getUser(connstr);
            LayTableModel<List<SYS_USER>> table = new LayTableModel<List<SYS_USER>>();
            table.message = "success";
            table.code = 200;
            table.total = model.Count;
            table.rows = new Rows<List<SYS_USER>>();
            table.rows.item = new List<SYS_USER>();
            table.rows.item = model;
            return JsonConvert.SerializeObject(table);
        }
        [PermitFilter]
        public IActionResult editUser(string id)
        {
            claim = (JwtClaim)_accessor.HttpContext.Items["user"];
            ViewBag.username = claim.username;
            ViewBag.area = claim.area;
            List<SYS_USER> model = SystemService.getUser(connstr);
            var res = model.Where(m => m.ID == id).FirstOrDefault();
            ViewBag.model = res;
            return View();
        }

        [PermitFilter]
        public IActionResult addUser()
        {
            claim = (JwtClaim)_accessor.HttpContext.Items["user"];
            ViewBag.username = claim.username;
            ViewBag.area = claim.area;
            ViewBag.model = null;
            return View("editUser");
        }
        [PermitFilterAttribute]
        [HttpPost]
        public ResponseResult<string> addUser([FromQuery]string token, string username, int area, string password,string email)
        {
            claim = (JwtClaim)_accessor.HttpContext.Items["user"];
            try
            {
                if (string.IsNullOrEmpty(username)||string.IsNullOrEmpty(password)||area==0)
                {
                    return ResponseResult<string>.Error("参数异常");
                }
                SYS_USER room = new SYS_USER { ID=Guid.NewGuid().ToString(),USERNAME=username,PASSWORD=MD5Utils.decode(password),AREA=area,EMAIL=email,UPDATETIME=DateTime.Now};
                var b = SystemService.addUser(room, connstr);
                if (b)
                {
                    return ResponseResult<string>.Success("操作成功", "操作成功");
                }
                else
                {
                    return ResponseResult<string>.Success("操作失败", "操作失败");
                }
            }
            catch (Exception ex)
            {
                return ResponseResult<string>.Error("系统异常");
            }
        }
        [PermitFilter]
        public IActionResult editPwd() {
            claim = (JwtClaim)_accessor.HttpContext.Items["user"];
            return View();
        }
        [PermitFilterAttribute]
        [HttpPost]
        public ResponseResult<string> editPwd([FromQuery]string token, string name, int area, string oldpwd, string newpwd)
        {
            claim = (JwtClaim)_accessor.HttpContext.Items["user"];
            try
            {
                var user=SystemService.getUser(connstr).Where(u => u.USERNAME == name.Trim() && u.AREA == area&&u.PASSWORD==MD5Utils.decode(oldpwd)).FirstOrDefault();
                if (user==null)
                {
                    return ResponseResult<string>.Error("密码验证不通过");
                }
                var PASSWORD = MD5Utils.decode(newpwd);
                var b = SystemService.editUserPwd(user.ID,PASSWORD, connstr);
                if (b)
                {

BCR/Controllers/SystemController.cs
using BCR.Models;
using Interfaces;
using Interfaces.Impl;
using Library;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Models;
using Newtonsoft.Json;
using System;

namespace BCR.Controllers
{

    public class SystemController : Controller
    {
        public ISystemService systemService;
        private ISystemService SystemService
        {
            get
            {
                if (systemService == null)
                {
                    systemService = new SystemService();
                }
                return systemService;
            }
        }
        public static string connstr = "";
        public static IHttpContextAccessor _accessor;
        public readonly IConfiguration _configuration;
        public SystemController(IHttpContextAccessor accessor, IConfiguration configuration)
        {
            _accessor = accessor;
            _configuration = configuration;
            connstr = configuration["connstr:mysql"];
        }
        [NoPermissionRequired]
        public IActionResult Login()
        {
            return View();
        }
        [NoPermissionRequired]
        public ResponseResult<string> PostLogins(string username, string password)
        {
            if (!string.IsNullOrEmpty(username.Trim()) && !string.IsNullOrEmpty(password.Trim()))
            {
                try
                {
                    string token = "";
                    password = MD5Utils.decode(password);
                    var user = SystemService.AuthUser(username, password, connstr);
                    if (user != null)
                    {
                        JwtUtils jwt = new JwtUtils();
                        JwtHeader header = new JwtHeader();
                        header.alg = AlgEnum.HS256;
                        JwtClaim claim = new JwtClaim();
                        claim.isadmin = user.AREA == 0 ? true : false;
                        claim.area = user.AREA;
                        claim.uid = user.ID;
                        claim.username = user.USERNAME;
                        claim.exp = DateTime.Now.AddMinutes(30).ToBinary();
                        token = jwt.EncodingJwt(header, claim);
                        return ResponseResult<string>.Success(token, "登录成功");
                    }
                }
                catch (Exception ex)
                {
                    Console.Write(ex.Message);
                    return ResponseResult<string>.Error("登录失败");
                }
            }
            return ResponseResult<string>.Error("登录失败");
        }
        [NoPermissionRequired]
        public IActionResult Logout()
        {
            //应该清除localstorage
            return View("Login");
        }
        [NoPermissionRequired]
        public IActionResult Error()
        {
            return View();
        }

    }
}

BCR/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@RenderSection("Title") - BCR</title>
    <link rel="stylesheet" type="text/css" media="screen" href="~/lib/lib/layui/css/layui.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="~/lib/lib/layer-v3.1.1/theme/default/layer.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="~/lib/lib/layui/tb.css" />
    <script src="~/lib/lib/timeselect/js/jquery-1.9.1.js"></script>
    <script src="~/lib/lib/layui/layui.js"></script>
    <script src="~/lib/jquery.cookie.js"></script>

</head>
<body class="layui-layout-body">
    <div class="layui-layout layui-layout-admin">
        <div class="layui-header">
            <div class="layui-logo">BCR</div>
            <ul class="layui-nav layui-layout-left">
                <li class="layui-nav-item"><a onclick="goto('/Home/Index')" href="#">待办事项</a></li>
                @{
                    if (ViewBag.area != 0)
                    {
                        <li class="layui-nav-item"><a onclick="goto('/Room/Show')" href="#">会议室</a></li>
                        <li class="layui-nav-item"><a onclick="goto('/Project/Index')" href="#">项目</a></li>
                        <li class="layui-nav-item"><a onclick="goto('/Report/Weekly')" href="#">周报</a></li>
                        <li class="layui-nav-item"><a onclick="goto('/Report/Monthly')" href="#">月报</a></li>
                    }
                }

            </ul>
            <ul class="layui-nav layui-layout-right">
                <li class="layui-nav-item" onclick="showuserinfo('@ViewBag.username','@ViewBag.area')">
                    <a href="javascript:;">
                        <img src="~/lib/lib/layui/images/tx.jpg" class="layui-nav-img">
                        @ViewBag.username
                    </a>
                </li>
                <li class="layui-nav-item"><a asp-controller="System" asp-action="Logout">退了</a></li>
            </ul>
        </div>
            <!-- 内容主体区域 -->
            <div class="layui-card">
                @RenderBody()
            </div>
        <div class="layui-footer" style="left:0px;">
            <!-- 底部固定区域 -->
            © shaksper
        </div>
    </div>
        
        @RenderSection("Scripts", required: false)
</body>
</html>
<script>
    //JavaScript代码区域
    layui.use('element', function () {
        var element = layui.element;

    });
    layui.use('layer', function () {
        var layer = layui.layer;
        
    });
    function goto(url) {
        var storage = window.localStorage;
        token=storage.getItem("token");
        window.location = url + "?token=" + token;
    }
    function showuserinfo(uname, area) {
        var storage = window.localStorage;
        token = storage.getItem("token");
        layer.open({
                    type: 2,
            title: '修改密码',
            content: '@Url.Action("editPwd","Admin")?token=' + token,
                    area: ['400px', '300px'],
                        yes: function (index, layero) {
                            var body =top.layer.getChildFrame('body', index);
                            var oldpwd = body.find('#oldpwd').val()
                            var newpwd = body.find("#newpwd").val();
                            var renewpwd = body.find("#renewpwd").val();
                            if (newpwd != renewpwd) {
                                layer.msg("输入不一致");
                                return false;
                            }
                            var parm = { name: uname, area: area, oldpwd: oldpwd, newpwd: newpwd };
                            //loading层
                            var index1 = layer.load(1, {
                                shade: [0.1, '#fff'] //0.1透明度的白色背景
                            });
                            $.post("@Url.Action("editPwd","Admin")?token=" + token, parm, function (res) {
                                var msg = JSON.stringify(res);
                                var jmsg = JSON.parse(msg);
                                layer.close(index1);
                                layer.msg(jmsg.message);
                                if (jmsg.status == 1) {
                                    storage.removeItem("token");
                                    layer.close(index);
                                    window.location.href = "@Url.Action("Login","System")";
                                }
                            });

                    },
                    btn: ['确定', '取消'],

                });
    }
    
</script>